import os
import subprocess
import sys
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from alembic import command
from app.db.base import Base

BACKEND_DIRECTORY = Path(__file__).resolve().parents[1]


def run_alembic(database_url: str, *arguments: str) -> subprocess.CompletedProcess[str]:
    environment = {**os.environ, "DATABASE_URL": database_url, "APP_ENV": "test"}
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", "alembic.ini", *arguments],
        cwd=BACKEND_DIRECTORY,
        env=environment,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return result


def test_migration_matches_models_and_can_round_trip(tmp_path: Path) -> None:
    database_url = f"sqlite+pysqlite:///{(tmp_path / 'migration-test.db').as_posix()}"
    run_alembic(database_url, "upgrade", "head")
    engine = create_engine(database_url)
    try:
        tables = set(inspect(engine).get_table_names())
        assert tables - {"alembic_version"} == set(Base.metadata.tables)
    finally:
        engine.dispose()

    run_alembic(database_url, "check")
    run_alembic(database_url, "downgrade", "base")
    engine = create_engine(database_url)
    try:
        assert set(inspect(engine).get_table_names()) <= {"alembic_version"}
    finally:
        engine.dispose()

    run_alembic(database_url, "upgrade", "head")
    run_alembic(database_url, "check")


def test_injected_version_schema_excludes_only_alembic_table(tmp_path: Path) -> None:
    engine = create_engine(f"sqlite+pysqlite:///{(tmp_path / 'injected.db').as_posix()}")
    config = Config(str(BACKEND_DIRECTORY / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIRECTORY / "alembic"))
    config.attributes["version_table_schema"] = "main"
    try:
        with engine.connect() as connection:
            config.attributes["connection"] = connection
            command.upgrade(config, "head")
            command.check(config)
            connection.execute(text("CREATE TABLE unexpected_table (id INTEGER PRIMARY KEY)"))
            connection.commit()
            with pytest.raises(AutogenerateDiffsDetected, match="unexpected_table"):
                command.check(config)
    finally:
        engine.dispose()
